# Generated by Django 5.1.7 on 2025-03-31 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_usermod_options_usermod_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField(verbose_name='telegram id')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='foydalanuvchi ism')),
                ('full_name', models.CharField(max_length=150, verbose_name="to'liq ism")),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Adminlar',
            },
        ),
    ]
